---
title: "ST2195_CA001"
output: html_document
date: "2023-10-26"
---

### Load the library

Install the `rvest` package if it is not yet installed

```{r}
if (!("rvest" %in% installed.packages())) {
  install.packages("rvest")
}
library(rvest)
```

Load in the html

Get the csv examples under the headers "States" and "Abbreviations" using pipeline "%\>%" result from previous function %\>% as input to next function

```{r}
url <- "https://simple.wikipedia.org/wiki/List_of_U.S._states_by_traditional_abbreviation"
webpage_html <- read_html(url)
all_tables <- webpage_html %>%
  html_nodes("table")
states_data <- all_tables[[1]] # Assuming it's the first table
states_data <- states_data %>%
    html_table(fill=TRUE)
```

Extract only essential columns

```{r}
selected_columns <- states_data[, c(1,3)]
colnames(selected_columns) <- c("State", "Abbreviations")
```

### Save the csv example into a csv file

```{r}
write.csv(selected_columns, file = "states_abbreviations.csv", row.names=FALSE)
```

```{r}
read.csv("states_abbreviations.csv")
```
